site_name: illyria Documentation
nav:
  - Introduction: index.md
  - illyriaFactions:
    - Home: illyriafactions/index.md
    - Installation: illyriafactions/installation.md
    - Commands: illyriafactions/commands.md
    - Permissions: illyriafactions/permissions.md
    - Placeholders: illyriafactions/placeholders.md
    - 'Default Files': illyriafactions/defaultfiles.md
    - 'Default Permissions': illyriafactions/defaultperms.md
    - 'Configurable Map': illyriafactions/configurablemap.md
    - 'Skript Integration': illyriafactions/skriptintegration.md
    - 'Factions API': illyriafactions/factionsapi.md
  - illyriaBuckets:
    - Home: illyriabuckets/index.md
    - Installation: illyriabuckets/installation.md
    - Commands: illyriabuckets/commands.md
    - Permissions: illyriabuckets/permissions.md
    - Placeholders: illyriabuckets/placeholders.md
    - Default Files: illyria
  - illyriaCollectors:
    - Home: illyriacollectors/index.md
    - Installation: illyriacollectors/installation.md
    - Commands: illyriacollectors/commands.md
    - Permissions: illyriacollectors/permissions.md
    - Placeholders: illyriacollectors/placeholders.md
    - Default Files: illyria
  - illyriaDiscord:
    - Home: illyriadiscord/index.md
    - Installation: illyriadiscord/installation.md
    - Commands: illyriadiscord/commands.md
    - Permissions: illyriadiscord/permissions.md
    - Placeholders: illyriadiscord/placeholders.md
    - Default Files: illyria
  - illyriaFTOP:
    - Home: illyriaftop/index.md
    - Installation: illyriaftop/installation.md
    - Commands: illyriaftop/commands.md
    - Permissions: illyriaftop/permissions.md
    - Placeholders: illyriaftop/placeholders.md
    - Default Files: illyria
  - illyriaOutpost:
    - Home: illyriaoutpost/index.md
    - Installation: illyriaoutpost/installation.md
    - Commands: illyriaoutpost/commands.md
    - Permissions: illyriaoutpost/permissions.md
    - Placeholders: illyriaoutpost/placeholders.md
    - Default Files: illyria
  - ObsidianBreaker:
    - Home: obsidianbreaker/index.md
    - Installation: obsidianbreaker/installation.md
    - Commands: obsidianbreaker/commands.md
    - Permissions: obsidianbreaker/permissions.md
    - Placeholders: obsidianbreaker/placeholders.md
    - Default Files: obsidianbreaker/defaultfiles.md
dev_addr: '0.0.0.0:8080'
theme:
  name: 'material'
extra_css:
  - extra.css
site_author: 'illyria'
site_description: The wiki site for illyria's products
docs_dir: 'docs'
site_dir: 'site'
plugins:
  - search
