site_name: Illyria Documentation
nav:
  - Introduction: index.md
  - illyriaFactions:
    - Home: illyriafactions/index.md
    - Commands: illyriafactions/commands.md
    - 'Default Permissions': illyriafactions/defaultperms.md
    - Permissions: illyriafactions/permissions.md
    - 'Configurable Map': illyriafactions/configurablemap.md
    - 'Skript Integration': illyriafactions/skriptintegration.md
    - 'Claiming System Factions': illyriafactions/systemfactionclaiming.md
    - 'Factions API': illyriafactions/factionsapi.md
    - Installation: illyriafactions/installation.md
    - 'Default Files': illyriafactions/defaultfiles.md
  - illyriaCore:
    - Home: illyriacore/index.md
    - 'Getting Started': illyriacore/gettingstarted.md
    - Features: illyriacore/features.md
    - Permissons: illyriacore/permissons.md
    - 'Default Files': illyriacore/defaultfiles.md
dev_addr: '0.0.0.0:8080'
theme:
  name: 'material'
