site_name: Illyria Documentation
nav:
  - Introduction: index.md
  - IllyriaCore:
    - Home: illyriacore/index.md
    - Installation: illyriacore/installation.md
    - 'Getting Started': illyriacore/gettingstarted.md
    - Features: illyriacore/features.md
    - Commands: illyriacore/commands.md
    - Permissions: illyriacore/permissions.md
    - Placeholders: illyriacore/placeholders.md
    - 'Default Files': illyriacore/defaultfiles.md
  - IllyriaFactions:
    - Home: illyriafactions/index.md
    - Commands: illyriafactions/commands.md
    - 'Default Permissions': illyriafactions/defaultperms.md
    - Permissions: illyriafactions/permissions.md
    - 'Configurable Map': illyriafactions/configurablemap.md
    - 'Skript Integration': illyriafactions/skriptintegration.md
    - 'How To':
      - Index: illyriafactions/howto.md
      - 'Factions Map': illyriafactions/fmap.md
      - 'Claiming System Factions': illyriafactions/systemfactionclaiming.md
    - 'Factions API': illyriafactions/factionsapi.md
    - Installation: illyriafactions/installation.md
    - 'Default Files': illyriafactions/defaultfiles.md
    - Placeholders: illyriafactions/placeholders.md
  - IllyriaBuckets:
    - Home: illyriabuckets/index.md
    - Installation: illyriabuckets/installation.md
    - Commands: illyriabuckets/commands.md
    - Permissions: illyriabuckets/permissions.md
    - Placeholders: illyriabuckets/placeholders.md
  - IllyriaCollectors:
    - Home: illyriacollectors/index.md
    - Installation: illyriacollectors/installation.md
    - Commands: illyriacollectors/commands.md
    - Permissions: illyriacollectors/permissions.md
    - Placeholders: illyriacollectors/placeholders.md
  - IllyriaDiscord:
    - Home: illyriadiscord/index.md
    - Installation: illyriadiscord/installation.md
    - Commands: illyriadiscord/commands.md
    - Permissions: illyriadiscord/permissions.md
    - Placeholders: illyriadiscord/placeholders.md
  - IllyriaFTop:
    - Home: illyriaftop/index.md
    - Installation: illyriaftop/installation.md
    - Commands: illyriaftop/commands.md
    - Permissions: illyriaftop/permissions.md
    - Placeholders: illyriaftop/placeholders.md
  - IllyriaOutpost:
    - Home: illyriaoutpost/index.md
    - Installation: illyriaoutpost/installation.md
    - Commands: illyriaoutpost/commands.md
    - Permissions: illyriaoutpost/permissions.md
    - Placeholders: illyriaoutpost/placeholders.md
  - ObsidianBreaker:
    - Home: obsidianbreaker/index.md
    - Installation: obsidianbreaker/installation.md
    - Commands: obsidianbreaker/commands.md
    - Permissions: obsidianbreaker/permissions.md
    - Placeholders: obsidianbreaker/placeholders.md
dev_addr: '0.0.0.0:8080'
theme:
  name: 'material'
extra_css:
  - extra.css
site_author: 'Illyria'
site_description: 'The Wiki site for Illyria\'s products.'
docs_dir: 'docs'
site_dir: 'site'
plugins:
  - search
