site_name: Factions Wiki
nav:
  - Home: index.md
  - Commands: commands.md
  - DefaultPermissions: defaultperms.md
  - Permissions: permissions.md
  - ConfigurableMap: configurablemap.md
  - SkriptIntegration: skriptintegration.md
  - Claiming-System-Factions: systemfactionclaiming.md
  - FactionsAPI: factionsapi.md
  - Installation: installation.md
theme: cyborg